### ISSUE TITLE
`generate` in latest arm docker does not work

### ISSUE THREAD

**Issue by sbkg0002** [mitchellrj/hue_exporter#2]
Hi,

First of all; many thanks for creating this exporter!

The `generate` function of armv7 docker build crashes:
```
$ docker run -it --rm --entrypoint /bin/hue_exporter mitchellrj/hue_exporter:latest-arm7 generate
INFO[0000] Starting hue_exporter (version=0.2.2, branch=master, revision=cea677bb6afc96e50885cc6d347ca0faf165a939)  source="main.go:117"
INFO[0000] Build context (go=go1.12, user=root, date=20190319-22:02:00)  source="main.go:118"
panic: Error while searching for Hue bridges on the local network: unable to locate bridge


goroutine 1 [running]:
main.generateConfig(0x1c0e200)
	/go/src/github.com/mitchellrj/hue_exporter/generate.go:16 +0x500
main.main()
	/go/src/github.com/mitchellrj/hue_exporter/main.go:123 +0x428
```
Any ideas? I cant do Go, so cant fix it :(

**Comment by gpkvt** [comment]
Seems to be a general problem. But you can create the config by hand, just execute the following command during the first 30 seconds after you pressed the button on your hue bridge:

```curl --data "{\"devicetype\": \"hue_exporter#hue_exporter\"}" http://<YOUR_BRIDGE_IP>/api```

You will get an username in return. Use this as API-Key in your hue_exporter.yml (see hue_exporter.example.yml for details).
